### ISSUE TITLE
Progress Tracker: Queue class methods

### ISSUE THREAD

**Issue by klaudiosinani** [klaussinani/kiu#3]
## Description

The following issue will act as a progress tracking thread, regarding the implementation of the exposed `Queue` class methods:

### Queue Methods

- [x] `Queue#length`
- [x] `Queue#clear()`
- [x] `Queue#dequeue()`
- [x] `Queue#enqueue(value)`
- [x] `Queue#forEach(fn)`
- [x] `Queue#includes(value)`
- [x] `Queue#isEmpty()`
- [x] `Queue#map(fn)`
- [x] `Queue#nth(n)`
- [x] `Queue#peekFirst()`
- [x] `Queue#peekLast()`
- [x] `Queue#reverse()`
- [x] `Queue#rotateLeft(n)`
- [x] `Queue#rotateRight(n)`
- [x] `Queue#toArray()`
